package com.pengyuan.pims.common;

import org.springframework.jdbc.core.JdbcTemplate;

import java.sql.Connection;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * PG 迁移 v11.9：SQLite/PostgreSQL DDL 方言翻译与统一执行入口。
 *
 * 背景：33 个 SchemaInitializer 手写了 74 张 SQLite 版建表语句。为让同一份代码跑两种库，
 * 这里在运行期把 SQLite DDL 翻译成 PG 等价物（PG 同样支持 CREATE TABLE/INDEX IF NOT EXISTS），
 * 初期双库并存，PG 稳定后删除 SQLite 分支。
 *
 * 翻译规则（只作用于 DDL 文本，幂等执行前翻译一次）：
 *  1. INTEGER PRIMARY KEY AUTOINCREMENT → BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
 *     （BY DEFAULT 允许显式插入 id——数据迁移保 ID 的前提；GENERATED ALWAYS 会拒显式值）
 *  2. 已知布尔列（见 BOOLEAN_COLUMNS，来自全部实体 public Boolean 字段）INTEGER → BOOLEAN，
 *     且该列 DEFAULT 1/0 → DEFAULT TRUE/FALSE（PG 布尔不接受整型默认值）
 *  3. TIMESTAMP / DATE → BIGINT：全项目时间毫秒存储（JdbcTemplate 直查返回毫秒 long），
 *     PG 端继续保持毫秒 bigint，实体层由 LocalDateTimeMillisConverter/LocalDateMillisConverter
 *     全局转换，原生 SQL 全部不用改
 *  4. 其余裸 INTEGER → BIGINT（数量/金额精度无损）
 *  5. REAL → DOUBLE PRECISION（SQLite REAL 为 8 字节浮点）；BLOB → BYTEA
 *  6. DEFAULT 里的 (strftime('%s','now')*1000)/CURRENT_TIMESTAMP → now_ms()（PG 兼容函数，见 PgCompatFunctionsInitializer）；
 *     strftime('%s','now')*1000 类默认值依赖兼容函数，原样保留
 */
public final class SqlDdl {

    private SqlDdl() {}

    /** 全部实体 public Boolean 字段对应的列名（ snake_case ）——DDL 翻译时 INTEGER→BOOLEAN */
    private static final Set<String> BOOLEAN_COLUMNS = Set.of(
            "blacklisted", "closed", "credit_exceeded", "enabled",
            "gen_finance", "is_default", "is_free", "is_primary", "must_change_pwd");

    private static volatile Boolean pg = null;

    /** 进程级缓存的数据库类型判定（初始器都在启动期串行执行，无需加锁重查） */
    public static boolean isPostgreSQL(JdbcTemplate jdbc) {
        if (pg == null) {
            synchronized (SqlDdl.class) {
                if (pg == null) {
                    try (Connection c = jdbc.getDataSource().getConnection()) {
                        pg = "PostgreSQL".equalsIgnoreCase(c.getMetaData().getDatabaseProductName());
                    } catch (Exception e) {
                        throw new IllegalStateException("数据库类型判定失败: " + e.getMessage(), e);
                    }
                }
            }
        }
        return pg;
    }

    private static final Pattern PAT_AUTOINCREMENT = Pattern.compile(
            "(?i)\\bINTEGER\\s+PRIMARY\\s+KEY\\s+AUTOINCREMENT\\b");
    private static final Pattern PAT_TIMESTAMP = Pattern.compile("(?i)\\bTIMESTAMP\\b");
    private static final Pattern PAT_DATETIME = Pattern.compile("(?i)\\bDATETIME\\b");
    private static final Pattern PAT_DATE = Pattern.compile("(?i)\\bDATE\\b");
    private static final Pattern PAT_INTEGER = Pattern.compile("(?i)\\bINTEGER\\b");
    private static final Pattern PAT_REAL = Pattern.compile("(?i)\\bREAL\\b");
    private static final Pattern PAT_BLOB = Pattern.compile("(?i)\\bBLOB\\b");
    private static final Pattern PAT_DEFAULT_NOW = Pattern.compile(
            "(?i)DEFAULT\\s*\\(\\s*(?:datetime\\('now'(?:\\s*,\\s*'\\+8 hours')?\\)|CURRENT_TIMESTAMP)\\s*\\)");

    /** SQLite DDL → PostgreSQL DDL（非 PG 环境原样返回） */
    public static String translateDdl(String sql) {
        if (pg == null || !pg) return sql;
        String s = sql;
        // 1. AUTOINCREMENT 主键（须最先，否则下面的 INTEGER 规则会先改写类型词）
        s = PAT_AUTOINCREMENT.matcher(s).replaceAll("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
        // 2. 已知布尔列：INTEGER → BOOLEAN，DEFAULT 1/0 → TRUE/FALSE
        for (String col : BOOLEAN_COLUMNS) {
            s = Pattern.compile("(?i)(\\b" + col + "\\s+)INTEGER(\\s+DEFAULT\\s+)1\\b")
                    .matcher(s).replaceAll("$1BOOLEAN$2TRUE");
            s = Pattern.compile("(?i)(\\b" + col + "\\s+)INTEGER(\\s+DEFAULT\\s+)0\\b")
                    .matcher(s).replaceAll("$1BOOLEAN$2FALSE");
            s = Pattern.compile("(?i)\\b" + col + "\\s+INTEGER\\b")
                    .matcher(s).replaceAll(col + " BOOLEAN");
        }
        // 3/4. 时间列与剩余整型统一 BIGINT
        s = PAT_TIMESTAMP.matcher(s).replaceAll("BIGINT");
        s = PAT_DATETIME.matcher(s).replaceAll("BIGINT");
        s = PAT_DATE.matcher(s).replaceAll("BIGINT");
        s = PAT_INTEGER.matcher(s).replaceAll("BIGINT");
        // 5. REAL / BLOB
        s = PAT_REAL.matcher(s).replaceAll("DOUBLE PRECISION");
        s = PAT_BLOB.matcher(s).replaceAll("BYTEA");
        // 6. DEFAULT 当前时间 → 毫秒函数（含 (strftime('%s','now')*1000) 形态，PG 兼容函数返回 TEXT 不可算术）
        s = PAT_DEFAULT_NOW.matcher(s).replaceAll("DEFAULT (now_ms())");
        s = s.replace("(strftime('%s','now')*1000)", "now_ms()");
        s = s.replace("(strftime('%s', 'now') * 1000)", "now_ms()");
        // 7. 源码里已写 BOOLEAN DEFAULT 1/0 的（历史 ALTER ADD 语句）——PG 布尔默认值不接受整型字面量
        s = s.replaceAll("(?i)(\\bBOOLEAN\\s+DEFAULT\\s+)1\\b", "$1TRUE");
        s = s.replaceAll("(?i)(\\bBOOLEAN\\s+DEFAULT\\s+)0\\b", "$1FALSE");
        return s;
    }

    /** 统一 DDL 执行入口：所有 SchemaInitializer 的 jdbc.execute(...) 改走这里 */
    public static void exec(JdbcTemplate jdbc, String sql) {
        jdbc.execute(translateDdl(sql));
    }
}
